name: Make keystore
on: workflow_dispatch
jobs:
  key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21 }
      - run: |
          keytool -genkeypair -keystore upload.jks -alias upload -keyalg RSA -keysize 2048 -validity 10000 -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -keypass "${{ secrets.KEYSTORE_PASSWORD }}" -dname "CN=Sky parkour runner"
          base64 -w0 upload.jks > upload.jks.b64
      - uses: actions/upload-artifact@v4
        with: { name: keystore, path: "upload.jks*" }
